### ISSUE TITLE
Optionally ignore casing

### ISSUE THREAD

**Issue by shinmen14** [johntimothybailey/chai-sorted#1]
Hi,

It looks like the sorting check fails when a string has an upper case letter in the middle. For instance, the following scenario fails the check:

`expect([{name: "Dedoto"}, {name: "DeSoto"}]).to.be.sortedBy('name');`

If I change the S to s, it will work as expected:

`expect([{name: "Dedoto"}, {name: "Desoto"}]).to.be.sortedBy('name');`

I'm currently testing an endpoint that returns an array of US cities and the test case was failing because of that specific scenario. It turns out DeSoto is an actual city located in Texas.

Let me know if you need any additional information.

Thanks.

**Comment by johntimothybailey** [comment]
@shinmen14 'DeSoto' weighs differently than 'Desoto' and even 'desoto' Basically, capital letters in javascript compare differently than lower case, so while they look like they 'DeSoto' should be after 'Dedoto' that is not the case unless we push them to the same case

Take for instance,
```
['Dedoto', 'DeSoto'].sort() 
// outputs ["DeSoto", "Dedoto"]

'S'.charCodeAt(0)
// outputs 83
's'.charCodeAt(0)
// outputs 115
```

#2  suggests changing the API a bit to allow for a more explicit usage. I could add something similar to `sortedBy('name', {ignoreCase: true})`

What do you think?

**Comment by johntimothybailey** [comment]
@shinmen14 due to response time, I'm going to assume the best compromise is for a feature enhancement allowing. If you have any further thoughts on the matter I'm more than happy to incorporate those as well.

**Comment by NoxPhoenix** [comment]
Came here looking for just this. I figured I would help out and open a PR to add this enhancement.
https://github.com/johntimothybailey/chai-sorted/pull/12

**Comment by RayeesMir** [comment]
```
const keys = ['A', 'AN', 'AO', 'AL', 'Al', 'Ali', 'AP']
const sortedKeys = keys.sort((a, b) => a - b)
expect(sortedKeys).to.be.sorted()
```
why this isn't working? 
shouldn't this work?
