### ISSUE TITLE
sorted(false) false negative for descending input

### ISSUE THREAD

**Issue by jamwaffles** [johntimothybailey/chai-sorted#2]
The documentation states that `expect(...).to.be.sorted(false)` should assert that an array is sorted in descending order, which is not the case. Changing this to `expect(...).to.be.sorted(true)` gives the correct behaviour. I can have a PR ready to go for this, but I want to figure out what the correct behaviour should be. I see two options:

- Update documentation to use `sorted(true)` to sort descending.
- Fix library so that passing `false` does indeed sort the right way. I think [the logic](https://github.com/johntimothybailey/chai-sorted/blob/master/lib/is.sorted.js#L7-L8) is a bit upside down at the moment.

A third option would be to change the API slightly so that passing `sorted({ descending: true })` would change the order. This would make usage more obvious and remove the usage of an opaque, but then again we have the `.to.be.descending`, _et al_ rules for that.

I added a failing unit test to my fork at 12ba8c78ce4b31e533c7bd1399ee22d87bd22659 which demonstrates the incorrect behaviour `sorted(false)`. Output:

![image](https://cloud.githubusercontent.com/assets/800791/26367915/0b7aaa46-3fe8-11e7-8f33-0ba159fb2492.png)

What's the best course of action here?

**Comment by johntimothybailey** [comment]
@jamwaffles Would you mind submitting the Pull Request?

**Comment by johntimothybailey** [comment]
I am fixing documentation and I like the idea of changing the API. Additionally, there were some API compatibility issues with Chai's API

**Comment by jamwaffles** [comment]
Sure, I'll update my fork from latest master. PR inbound soonish!

**Comment by jamwaffles** [comment]
#8 😁
