### ISSUE TITLE
Property assertions (ascending/descending) don't work

### ISSUE THREAD

**Issue by verheyenkoen** [johntimothybailey/chai-sorted#3]
The `.to.be.ascending` and `.to.be.descending` property assertions don't seem to work at all.

I cloned this repo, edited the tests and replaced "descending" with "ascending" and the test didn't fail.

I guess there's also not enough tests in this project. There are no tests that assertions fail when they should.

**Comment by johntimothybailey** [comment]
Hello @verheyenkoen thank you for the feedback! You're absolutely right! I usually do red-green-blue approach and I'm not sure what happened here. Apologies

I'm going through and updating the project right now.

Looking at this it seems that the `ascending` and `descending` simply do not work at this time.

**Comment by johntimothybailey** [comment]
@verheyenkoen 
I've updating the project to use the latest Chai API. It seems the previous implementation was no longer compatible.
Let me know if you have further issues!

**Comment by verheyenkoen** [comment]
Thanks
